src/game/server/gamerules.cpp
src/game/server/player.cpp

Implement team spawn feature.
Iterates over all info_player_deathmatch, if the info_player_deathmatch entity's team value matches the player's team, player spawns.

Team spawn feature

---

src/game/server/player.h
src/game/server/weapons.h

Add export for some methods and functions
This fixed weaponmod. Without this fix I have log errors:
```
L 01/24/2021 - 20:23:39: Start.
L 01/24/2021 - 20:23:39:  Version 0.9.241 Linux
L 01/24/2021 - 20:23:39:   Found hl.so at 0xf2bf8000
L 01/24/2021 - 20:23:39:    Error: "ClearMultiDamage" not found
L 01/24/2021 - 20:23:39:    Error: "ApplyMultiDamage" not found
L 01/24/2021 - 20:23:39:    Error: "UTIL_PrecacheOtherWeapon" not found
L 01/24/2021 - 20:23:39:    Error: "CBasePlayer::GetAmmoIndex" not found
L 01/24/2021 - 20:23:39:    Error: "CBasePlayer::GiveNamedItem" not found
L 01/24/2021 - 20:23:39:    Error: "CBasePlayer::SetAnimation" not found
L 01/24/2021 - 20:23:39:    Found "CBaseEntity::SUB_Remove" at 0xf2d15c8c
L 01/24/2021 - 20:23:39: Errors occurred. Please visit …
```

WeaponMod Loading Fix

---

src/game/client/CMakeLists.txt
src/game/client/net_linux.cpp

Client: Add linux networking

---

src/game/server/player.cpp

Add cvar mp_falldamage=2 to remove fall damage

---

.github/workflows/main.yml

Based on https://github.com/YaLTeR/OpenAG/commit/aeeb945ffc83cb0af720187c09e91ee00013bd08

CI: Monthly reporting

---

src/game/client/StudioModelRenderer.cpp

Based on https://github.com/YaLTeR/OpenAG/pull/124

Client: Added cl_viewmodel_hltv

---

src/game/client/StudioModelRenderer.cpp
src/game/client/StudioModelRenderer.h
src/game/client/hud.cpp
src/game/client/hud_update.cpp

No worries about CI, it will fixed after merge together with #74

Client: Added cl_viewmodel_fov

---

src/game/client/view.cpp

Based on https://github.com/YaLTeR/OpenAG/pull/121

Client: Added cl_bob_angled

---

src/game/client/hud.cpp
src/game/client/hud/CMakeLists.txt
src/game/client/hud/jumpspeed.cpp
src/game/client/hud/jumpspeed.h
src/game/client/view.cpp

Based on https://github.com/YaLTeR/OpenAG/pull/136

Client: Added hud_jumpspeed

---

src/game/client/in_camera.cpp

Based on https://github.com/YaLTeR/OpenAG/pull/102

Client: Disable thirdperson

---

src/game/client/in_camera.cpp

Based on https://github.com/YaLTeR/OpenAG/pull/142

Client: Added dem_forcehltv_local_model

---

src/game/client/hud/jumpspeed.cpp
src/game/client/hud/speedometer.cpp

Move jumpspeed below speedometer in default state

---

src/game/client/hud.cpp

See: https://github.com/YaLTeR/OpenAG/pull/153

Client: Added showtriggers for show trigger brushes

---

src/game/client/StudioModelRenderer.cpp

See: https://github.com/YaLTeR/OpenAG/pull/154

Client: Added r_drawentities 5 for hardware rendering

---

src/game/client/input.cpp

https://github.com/YaLTeR/OpenAG/pull/155

Client: Allow to interfere ducktapping process with manual +duck inputs

---

src/game/client/hud/ammo.cpp

may or may not have completely stolen this from @jovanlanik

Updated to include hud_fastswitch 2

---

.github/workflows/main.yml
scripts/BuildRelease.py

Updates actions to latest version and updates Ubuntu from 18.04 to 20.04. Resolves all GitHub Actions warnings.

CI updates

---

src/common/com_model.h
src/engine/eiface.h

Explained in https://github.com/YaLTeR/OpenAG/pull/175

Added undocumented function for enginefuncs_t and matched com_model.h with hardware and software engine versions

---

gamedir/delta.lst
scripts/BuildRelease.py

Source: https://github.com/tmp64/BugfixedHL/blob/master/gamedir/delta.lst

Server: Distribute delta.lst from deprecated BHL repo

---

src/game/client/input.cpp

Fixes #275
I didn't experience any side-effect when having or not LJ, doing bhop while using LJ, etc.

Fix unintended extra jump when using +jump and +ljump
